# Generated by Django 4.2.6 on 2023-10-13 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='role',
            field=models.CharField(default='user', max_length=50),
        ),
    ]
